import { z } from 'zod';

export const InstructTemplateSchema = z.object({
  name: z.string().min(1),
  systemSequence: z.string().default(''),
  systemPrefix: z.string().default(''),
  systemSuffix: z.string().default('\n'),
  inputSequence: z.string().default(''),
  inputSuffix: z.string().default('\n'),
  outputSequence: z.string().default(''),
  outputSuffix: z.string().default('\n'),
  firstOutputSequence: z.string().default(''),
  lastOutputSequence: z.string().default(''),
  firstInputSequence: z.string().default(''),
  lastInputSequence: z.string().default(''),
  stopSequence: z.string().default(''),
  systemSameAsUser: z.boolean().default(false),
  wrap: z.boolean().default(true),
  macro: z.boolean().default(true),
  namesBehavior: z.enum(['force', 'none', 'sample']).default('none'),
  userAlignmentMessage: z.string().default(''),
  storyStringTemplate: z.string().default(''),
  storyStringPrefix: z.string().default(''),
  storyStringSuffix: z.string().default(''),
  exampleSeparator: z.string().default(''),
  chatStart: z.string().default(''),
  activationRegex: z.string().default(''),
});

export type InstructTemplate = z.infer<typeof InstructTemplateSchema>;

export const DEFAULT_STORY_STRING_TEMPLATE =
  '{{#if system}}{{system}}\n{{/if}}{{#if description}}{{description}}\n{{/if}}{{#if personality}}{{personality}}\n{{/if}}{{#if scenario}}{{scenario}}\n{{/if}}{{#if persona}}{{persona}}\n{{/if}}{{trim}}';

export const CHAT_ML_TEMPLATE: InstructTemplate = {
  activationRegex: '',
  firstInputSequence: '',
  firstOutputSequence: '',
  chatStart: '',
  exampleSeparator: '',
  inputSequence: '<|im_start|>user\n',
  inputSuffix: '<|im_end|>\n',
  lastInputSequence: '',
  lastOutputSequence: '',
  macro: true,
  name: 'ChatML',
  namesBehavior: 'none',
  outputSequence: '<|im_start|>assistant\n',
  outputSuffix: '<|im_end|>\n',
  stopSequence: '',
  storyStringTemplate: DEFAULT_STORY_STRING_TEMPLATE,
  storyStringPrefix: '<|im_start|>system\n',
  storyStringSuffix: '<|im_end|>\n',
  systemSameAsUser: false,
  systemPrefix: '<|im_start|>system\n',
  systemSequence: '<|im_start|>system\n',
  systemSuffix: '<|im_end|>\n',
  userAlignmentMessage: '',
  wrap: true,
};

export const MISTRAL_TEMPLATE: InstructTemplate = {
  activationRegex: '',
  firstInputSequence: '',
  firstOutputSequence: '',
  chatStart: '',
  exampleSeparator: '',
  inputSequence: '[INST] ',
  inputSuffix: '',
  lastInputSequence: '',
  lastOutputSequence: '',
  macro: false,
  name: 'Mistral V2 & V3',
  namesBehavior: 'none',
  outputSequence: '',
  outputSuffix: '</s>',
  stopSequence: '',
  storyStringTemplate: DEFAULT_STORY_STRING_TEMPLATE,
  storyStringPrefix: '[INST] ',
  storyStringSuffix: '[/INST] Understood.</s>',
  systemSameAsUser: true,
  systemPrefix: '',
  systemSequence: '',
  systemSuffix: '',
  userAlignmentMessage: "Let's get started. Please respond based on the information and instructions provided above.",
  wrap: false,
};

export const ALPACA_TEMPLATE: InstructTemplate = {
  activationRegex: '',
  firstInputSequence: '',
  firstOutputSequence: '',
  chatStart: '',
  exampleSeparator: '',
  inputSequence: '### Instruction:\n',
  inputSuffix: '\n',
  lastInputSequence: '',
  lastOutputSequence: '',
  macro: false,
  name: 'Alpaca',
  namesBehavior: 'none',
  outputSequence: '### Response:\n',
  outputSuffix: '\n',
  stopSequence: '',
  storyStringTemplate: DEFAULT_STORY_STRING_TEMPLATE,
  storyStringPrefix: '### System:\n',
  storyStringSuffix: '\n',
  systemSameAsUser: false,
  systemPrefix: '### System:\n',
  systemSequence: '### System:\n',
  systemSuffix: '\n',
  userAlignmentMessage: '',
  wrap: true,
};

export const PLAIN_TEMPLATE: InstructTemplate = {
  activationRegex: '',
  firstInputSequence: '',
  firstOutputSequence: '',
  chatStart: '',
  exampleSeparator: '',
  inputSequence: '',
  inputSuffix: '\n\n',
  lastInputSequence: '',
  lastOutputSequence: '',
  macro: false,
  name: 'Plain',
  namesBehavior: 'none',
  outputSequence: '',
  outputSuffix: '\n\n',
  stopSequence: '',
  storyStringTemplate: DEFAULT_STORY_STRING_TEMPLATE,
  storyStringPrefix: '',
  storyStringSuffix: '\n\n',
  systemSameAsUser: false,
  systemPrefix: '',
  systemSequence: '',
  systemSuffix: '\n\n',
  userAlignmentMessage: '',
  wrap: false,
};

export const BUILT_IN_TEMPLATES: Array<InstructTemplate> = [
  CHAT_ML_TEMPLATE,
  MISTRAL_TEMPLATE,
  ALPACA_TEMPLATE,
  PLAIN_TEMPLATE,
];

export function normalizeSillyTavernInstruct(raw: Record<string, unknown>): InstructTemplate {
  return InstructTemplateSchema.parse({
    activationRegex: String(raw.activation_regex ?? ''),
    chatStart: '',
    exampleSeparator: '',
    firstInputSequence: String(raw.first_input_sequence ?? ''),
    firstOutputSequence: String(raw.first_output_sequence ?? ''),
    inputSequence: String(raw.input_sequence ?? raw.inputSequence ?? ''),
    inputSuffix: String(raw.input_suffix ?? ''),
    lastInputSequence: String(raw.last_input_sequence ?? ''),
    lastOutputSequence: String(raw.last_output_sequence ?? ''),
    macro: Boolean(raw.macro ?? true),
    name: String(raw.name ?? 'Imported'),
    namesBehavior: String(raw.names_behavior ?? raw.namesBehavior ?? 'none'),
    outputSequence: String(raw.output_sequence ?? raw.outputSequence ?? ''),
    outputSuffix: String(raw.output_suffix ?? ''),
    stopSequence: String(raw.stop_sequence ?? ''),
    storyStringTemplate: DEFAULT_STORY_STRING_TEMPLATE,
    storyStringPrefix: String(raw.story_string_prefix ?? ''),
    storyStringSuffix: String(raw.story_string_suffix ?? ''),
    systemSameAsUser: Boolean(raw.system_same_as_user ?? false),
    systemPrefix: String(raw.system_sequence ?? raw.systemPrefix ?? ''),
    systemSequence: String(raw.system_sequence ?? ''),
    systemSuffix: String(raw.system_suffix ?? ''),
    userAlignmentMessage: String(raw.user_alignment_message ?? ''),
    wrap: Boolean(raw.wrap ?? true),
  });
}

export function normalizeSillyTavernContext(raw: Record<string, unknown>): Pick<InstructTemplate, 'chatStart' | 'exampleSeparator' | 'name' | 'storyStringTemplate'> {
  return {
    chatStart: String(raw.chat_start ?? ''),
    exampleSeparator: String(raw.example_separator ?? ''),
    name: String(raw.name ?? 'Imported'),
    storyStringTemplate: String(raw.story_string ?? DEFAULT_STORY_STRING_TEMPLATE),
  };
}
